INSERT INTO RoomType (name, price, num_beds, total_available) VALUES ('Single Room', 70, 1, 5);
INSERT INTO RoomType (name, price, num_beds, total_available) VALUES ('Twin Bed',120, 2, 5);
INSERT INTO RoomType (name, price, num_beds, total_available) VALUES ('Queen',120, 1, 5);
INSERT INTO RoomType (name, price, num_beds, total_available) VALUES ('Executive',180, 1, 5);
INSERT INTO RoomType (name, price, num_beds, total_available) VALUES ('Suite',300, 2, 5);

INSERT INTO City (name) VALUES ('Sydney');
INSERT INTO City (name) VALUES ('Melbourne');
INSERT INTO City (name) VALUES ('Brisbane');
INSERT INTO City (name) VALUES ('Adelaide');
INSERT INTO City (name) VALUES ('Hobart');

INSERT INTO Consumer (email, pin, url) VALUES ('aaa@hotmail.com' , 1111, '111f8fd9-aabf-4d81-a353-6877388da78c'); 
INSERT INTO Consumer (email, pin, url) VALUES ('bbb@hotmail.com' , 2222, '018bdb1e-252c-4707-8038-422a048b0bf1'); 
INSERT INTO Consumer (email, pin, url) VALUES ('ccc@hotmail.com' , 3333, '269dab6e-2a45-45e1-92fc-9df86c5decc8'); 
INSERT INTO Consumer (email, pin, url) VALUES ('ddd@hotmail.com' , 4444, 'c5ae1ff9-4e4c-4001-b586-d4bfb96258db'); 
INSERT INTO Consumer (email, pin, url) VALUES ('eee@hotmail.com' , 5555, 'e8aa893e-ac78-4cc9-ba5e-77748e0dd25c');

INSERT INTO Booking (start_date, end_date, room_type_id, city_id, extra_bed, num_rooms, consumer_id, discount_id) VALUES ('2014-01-02', '2014-01-06', 1, 1, 0, 1, 1, null);
INSERT INTO Booking (start_date, end_date, room_type_id, city_id, extra_bed, num_rooms, consumer_id, discount_id) VALUES ('2014-02-04', '2014-02-12', 2, 2, 0, 1, 2, null);
INSERT INTO Booking (start_date, end_date, room_type_id, city_id, extra_bed, num_rooms, consumer_id, discount_id) VALUES ('2014-03-06', '2014-03-18', 3, 3, 0, 1, 3, null);
INSERT INTO Booking (start_date, end_date, room_type_id, city_id, extra_bed, num_rooms, consumer_id, discount_id) VALUES ('2014-04-08', '2014-04-24', 4, 4, 0, 1, 4, null);
INSERT INTO Booking (start_date, end_date, room_type_id, city_id, extra_bed, num_rooms, consumer_id, discount_id) VALUES ('2014-05-10', '2014-05-30', 5, 5, 0, 1, 5, null);

INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 1, null, 'available', 1);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 1, null, 'available', 1);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 1, null, 'available', 1);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 1, null, 'available', 1);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 1, null, 'available', 1);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 2, null, 'available', 1);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 2, null, 'available', 1);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 2, null, 'available', 1);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 2, null, 'available', 1);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 2, null, 'available', 1);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 3, null, 'available', 1);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 3, null, 'available', 1);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 3, null, 'available', 1);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 3, null, 'available', 1);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 3, null, 'available', 1);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 4, null, 'available', 1);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 4, null, 'available', 1);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 4, null, 'available', 1);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 4, null, 'available', 1);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 4, null, 'available', 1);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 5, null, 'available', 1);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 5, null, 'available', 1);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 5, null, 'available', 1);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 5, null, 'available', 1);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 5, null, 'available', 1);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 1, null, 'available', 2);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 1, null, 'available', 2);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 1, null, 'available', 2);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 1, null, 'available', 2);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 1, null, 'available', 2);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 2, null, 'available', 2);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 2, null, 'available', 2);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 2, null, 'available', 2);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 2, null, 'available', 2);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 2, null, 'available', 2);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 3, null, 'available', 2);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 3, null, 'available', 2);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 3, null, 'available', 2);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 3, null, 'available', 2);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 3, null, 'available', 2);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 4, null, 'available', 2);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 4, null, 'available', 2);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 4, null, 'available', 2);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 4, null, 'available', 2);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 4, null, 'available', 2);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 5, null, 'available', 2);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 5, null, 'available', 2);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 5, null, 'available', 2);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 5, null, 'available', 2);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 5, null, 'available', 2);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 1, null, 'available', 3);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 1, null, 'available', 3);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 1, null, 'available', 3);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 1, null, 'available', 3);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 1, null, 'available', 3);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 2, null, 'available', 3);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 2, null, 'available', 3);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 2, null, 'available', 3);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 2, null, 'available', 3);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 2, null, 'available', 3);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 3, null, 'available', 3);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 3, null, 'available', 3);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 3, null, 'available', 3);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 3, null, 'available', 3);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 3, null, 'available', 3);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 4, null, 'available', 3);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 4, null, 'available', 3);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 4, null, 'available', 3);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 4, null, 'available', 3);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 4, null, 'available', 3);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 5, null, 'available', 3);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 5, null, 'available', 3);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 5, null, 'available', 3);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 5, null, 'available', 3);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 5, null, 'available', 3);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 1, null, 'available', 4);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 1, null, 'available', 4);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 1, null, 'available', 4);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 1, null, 'available', 4);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 1, null, 'available', 4);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 2, null, 'available', 4);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 2, null, 'available', 4);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 2, null, 'available', 4);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 2, null, 'available', 4);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 2, null, 'available', 4);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 3, null, 'available', 4);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 3, null, 'available', 4);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 3, null, 'available', 4);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 3, null, 'available', 4);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 3, null, 'available', 4);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 4, null, 'available', 4);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 4, null, 'available', 4);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 4, null, 'available', 4);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 4, null, 'available', 4);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 4, null, 'available', 4);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 5, null, 'available', 4);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 5, null, 'available', 4);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 5, null, 'available', 4);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 5, null, 'available', 4);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 5, null, 'available', 4);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 1, null, 'available', 5);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 1, null, 'available', 5);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 1, null, 'available', 5);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 1, null, 'available', 5);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 1, null, 'available', 5);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 2, null, 'available', 5);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 2, null, 'available', 5);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 2, null, 'available', 5);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 2, null, 'available', 5);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 2, null, 'available', 5);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 3, null, 'available', 5);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 3, null, 'available', 5);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 3, null, 'available', 5);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 3, null, 'available', 5);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 3, null, 'available', 5);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 4, null, 'available', 5);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 4, null, 'available', 5);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 4, null, 'available', 5);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 4, null, 'available', 5);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 4, null, 'available', 5);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 5, null, 'available', 5);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 5, null, 'available', 5);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 5, null, 'available', 5);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 5, null, 'available', 5);
INSERT INTO Room (room_type_id, booking_id, status, city_id) VALUES ( 5, null, 'available', 5);

INSERT INTO Discount (room_type_id, start_date, end_date, city_id, reduced_rate) VALUES (1, '2014-03-01', '2014-03-25', 1, 0.1);